---
os: linux
dist: bionic

language: python
python:
  - "3.7"

services:
  - docker

# env:
#   global:
#     - ROLE_NAME: node_exporter
#   jobs:
#     - DISTRO: centos-8
#     - DISTRO: centos-7
#     - DISTRO: ubuntu-18.04
#     - DISTRO: ubuntu-16.04
#     - DISTRO: debian-buster
#     - DISTRO: debian-stretch
#     - DISTRO: debian-jessie

# addons:
#   sonarcloud:
#     organization: "tech-overlord-github"

before_install:
  - sudo apt-get update
  # - sudo apt-get upgrade -y
  - sudo apt-get install wget software-properties-common linux-headers-5.0.0-1026-gcp -y

install:
  - echo -e "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian bionic contrib" | sudo tee -a /etc/apt/sources.list.d/virtualbox.list
  - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install virtualbox-6.1 -y
  # - sudo /sbin/vboxconfig


#
# before_script:
#   # Rename project directory to actual Ansible Galaxy role name and switch to it.
#   - cd ../
#   - mv ansible-role-$ROLE_NAME darkwizard242.$ROLE_NAME
#   - cd darkwizard242.$ROLE_NAME
#
script:
  - sudo /sbin/vboxconfig
  # - sonar-scanner -Dsonar.projectVersion=$TRAVIS_BRANCH\_$TRAVIS_JOB_NUMBER
  # - molecule test
# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
