---
os: linux
dist: bionic

language: python
python:
  - "3.8"

services:
  - docker

env:
  global:
    - ROLE_NAME: node_exporter
    - VAGRANT_VERSION: 2.2.9
    - VAGRANT_OS_ARCH: linux_amd64
  jobs:
    # - DISTRO: centos-8
    # - DISTRO: centos-7
    - DISTRO: ubuntu2004
    - DISTRO: ubuntu1804
    - DISTRO: ubuntu1604
    - DISTRO: debian10
    - DISTRO: debian9


# addons:
#   sonarcloud:
#     organization: "tech-overlord-github"

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade -y
  - sudo apt-get install wget unzip software-properties-common linux-headers-$(uname -r) -y

install:
  - echo -e "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian bionic contrib" | sudo tee -a /etc/apt/sources.list.d/virtualbox.list
  - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install virtualbox-6.1 -y
  - sudo /sbin/vboxconfig
  - pip3 install molecule docker ansible-lint flake8 testinfra molecule-vagrant



before_script:
  # Rename project directory to actual Ansible Galaxy role name and switch to it.
  - cd ../
  - mv ansible-role-$ROLE_NAME darkwizard242.$ROLE_NAME
  - cd darkwizard242.$ROLE_NAME
#
script:
  - sudo wget https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_{VAGRANT_OS_ARCH}.zip &> /dev/null
  - sudo unzip vagrant_${VAGRANT_VERSION}_{VAGRANT_OS_ARCH}.zip -d /usr/local/bin/  &> /dev/null
  - sudo rm -rv vagrant_${VAGRANT_VERSION}_{VAGRANT_OS_ARCH}.zip
  - vagrant --version
  - vagrant up
  # - sonar-scanner -Dsonar.projectVersion=$TRAVIS_BRANCH\_$TRAVIS_JOB_NUMBER
  - molecule test
# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
