---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
  options:
    memory: 1024
    cpus: 1
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: ${BOX:-ubuntu1804}
    box: "darkwizard242/ansible${BOX:-ubuntu1804}"
provisioner:
  name: ansible
  log: true
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: testinfra
  options:
    verbose: true
